### ISSUE TITLE
bug? 把整个目录都复制了？

### ISSUE THREAD

**Issue by zz5678** [yujinqiu/pbadd#4]
在 系统 Documents 目录里 pbadd 了一个文件，剪贴板程序 paste 显示也是一个文件，但 粘贴到其他 finder 目录下时，把整个 Documents 目录都粘过去了

在其他目录里无法重现这个 bug

**Comment by zz5678** [comment]
再测试，发现是 pbadd 解析路径错误的 bug，不是 Documents 目录问题。
形如：
```
./filename.ext
```
点斜杠开头的，就会被 pbadd 当作父目录复制到剪贴板，但很奇怪的是 paste app 里看到剪贴板还是一个文件

![image](https://user-images.githubusercontent.com/67672527/119244290-917dc680-bba1-11eb-9b7b-0d04d35ae139.png)


![image](https://user-images.githubusercontent.com/67672527/119244279-524f7580-bba1-11eb-9963-d687791a3ac1.png)

如截图，左侧是正确剪贴版，右侧黏贴时，会把整个父目录贴上去 ……

**Comment by zz5678** [comment]
继续测试，纠正，不是上文说的父目录，而是 pbadd 把运行 pbadd 当前环境路径给复制到了剪贴板，但（可能的 mac 系统机制）tag 上还是正确的目标文件和文件夹。

看来mac 系统还可以「诱骗用户」啊！

**Comment by yujinqiu** [comment]
Fixed in v1.0.2, thanks for your feedback.  @zz5678
